# Generated by Django 3.1.7 on 2021-03-28 20:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=1)),
                ('customer_gender', models.CharField(max_length=10)),
                ('customer_income_group', models.CharField(max_length=10)),
                ('customer_region', models.CharField(max_length=10)),
                ('customer_marital_status', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('policy_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=50)),
                ('vehicle_segment', models.CharField(max_length=50)),
                ('premium', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000)])),
                ('bodily_injury_liability', models.IntegerField(default=0)),
                ('personal_injury_protection', models.IntegerField(default=0)),
                ('property_damage_liability', models.IntegerField(default=0)),
                ('collision', models.IntegerField(default=0)),
                ('comprehensive', models.IntegerField(default=0)),
                ('customers', models.ManyToManyField(blank=True, related_name='customers', through='insurance.Customer_Insurance', to='insurance.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer_insurance',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='insurance.insurance'),
        ),
    ]
